### ISSUE TITLE
Question: expand README.MD and explain how to setup development enviroment for developers

### ISSUE THREAD

**Issue by jodevsa** [kalkin/manager-new#5]
Hello @kalkin 

I'm having troubles setting up the **dev** environment and find the '**README**' instructions not enough for developers new to Qubes.

Could you please help ?

**Comment by kalkin** [comment]
Hi,

the whole Qubes-Builder Documentation is here: https://www.qubes-os.org/doc/qubes-builder

Also the mainstream development happens here https://github.com/QubesOS/qubes-desktop-linux-manager

**Comment by jodevsa** [comment]
TY.
